add list-item and typogr styles
Pro-Motion/centurion-cad-frontend-v1 pull request #1
Opened 2023-10-12 14:34 UTC by Polaolka

1- add .base-list-item, .character-list-item, .input-base-item classes 2 - add FONT STYLES in tailwind.config.js

2023-10-19 17:26 UTC, Vladislav-UZH requested changes

2023-10-23 20:23 UTC, Polaolka commented on src/assets/main.css
> +.character-list-item {
add class inheritance for styles

2023-10-23 20:24 UTC, Polaolka commented on tailwind.config.js
> +    fontSize: {
add base classes and add parameters in tailwind

2023-10-27 19:32 UTC, Polaolka commented on tailwind.config.js
> +    fontSize: {
add more understandable names in tailwind.config

2023-10-29 11:23 UTC, Vladislav-UZH approved these changes

2023-10-29 11:24 UTC, merged